"""empty message

Revision ID: 1233a25ed419
Revises: 2bce8ad583b6
Create Date: 2015-08-08 09:46:40.920030

"""

# revision identifiers, used by Alembic.
revision = '1233a25ed419'
down_revision = '2bce8ad583b6'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
