"""empty message

Revision ID: 1435a1539623
Revises: 3b465be0e664
Create Date: 2015-08-03 09:17:06.494392

"""

# revision identifiers, used by Alembic.
revision = '1435a1539623'
down_revision = '3b465be0e664'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('donors', 'password')
    op.drop_column('donors', 'email')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('donors', sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('donors', sa.Column('password', sa.VARCHAR(), autoincrement=False, nullable=False))
    ### end Alembic commands ###
