"""empty message

Revision ID: 14a519ffc608
Revises: None
Create Date: 2015-08-01 20:32:46.337572

"""

# revision identifiers, used by Alembic.
revision = '14a519ffc608'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('donors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column(u'donorinfo', sa.Column('donor_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'donorinfo', 'donors', ['donor_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'donorinfo', type_='foreignkey')
    op.drop_column(u'donorinfo', 'donor_id')
    op.drop_table('donors')
    ### end Alembic commands ###
