"""empty message

Revision ID: 17662481c28d
Revises: 50e07b758eeb
Create Date: 2015-08-03 07:12:30.066968

"""

# revision identifiers, used by Alembic.
revision = '17662481c28d'
down_revision = '50e07b758eeb'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
