"""empty message

Revision ID: 2042663de06d
Revises: 1233a25ed419
Create Date: 2015-08-08 09:52:46.117006

"""

# revision identifiers, used by Alembic.
revision = '2042663de06d'
down_revision = '1233a25ed419'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
