"""empty message

Revision ID: 2b55c0b0ad41
Revises: 1435a1539623
Create Date: 2015-08-04 06:31:07.565551

"""

# revision identifiers, used by Alembic.
revision = '2b55c0b0ad41'
down_revision = '1435a1539623'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('donors', sa.Column('uid', sa.String(), nullable=False))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('donors', 'uid')
    ### end Alembic commands ###
