"""empty message

Revision ID: 2bc9c11e348
Revises: 3498c1498ad
Create Date: 2015-08-04 07:05:29.144863

"""

# revision identifiers, used by Alembic.
revision = '2bc9c11e348'
down_revision = '3498c1498ad'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
