"""empty message

Revision ID: 2bce8ad583b6
Revises: 3b7ff83a9eb0
Create Date: 2015-08-08 09:40:01.107741

"""

# revision identifiers, used by Alembic.
revision = '2bce8ad583b6'
down_revision = '3b7ff83a9eb0'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
