"""empty message

Revision ID: 33b036dffb04
Revises: 2b55c0b0ad41
Create Date: 2015-08-04 06:43:09.203849

"""

# revision identifiers, used by Alembic.
revision = '33b036dffb04'
down_revision = '2b55c0b0ad41'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('donors', 'profile_url')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('donors', sa.Column('profile_url', sa.VARCHAR(), autoincrement=False, nullable=False))
    ### end Alembic commands ###
