"""empty message

Revision ID: 3498c1498ad
Revises: 42408fd96a15
Create Date: 2015-08-04 07:03:21.821723

"""

# revision identifiers, used by Alembic.
revision = '3498c1498ad'
down_revision = '42408fd96a15'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
