"""empty message

Revision ID: 3b7ff83a9eb0
Revises: 9263a4bff4e
Create Date: 2015-08-08 07:28:22.895543

"""

# revision identifiers, used by Alembic.
revision = '3b7ff83a9eb0'
down_revision = '9263a4bff4e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('donorinfo', sa.Column('uid', sa.String(), nullable=False))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('donorinfo', 'uid')
    ### end Alembic commands ###
