"""empty message

Revision ID: 42408fd96a15
Revises: 33b036dffb04
Create Date: 2015-08-04 06:56:00.354871

"""

# revision identifiers, used by Alembic.
revision = '42408fd96a15'
down_revision = '33b036dffb04'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('donors', 'access_token',
               existing_type=sa.VARCHAR(),
               nullable=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('donors', 'access_token',
               existing_type=sa.VARCHAR(),
               nullable=True)
    ### end Alembic commands ###
