"""empty message

Revision ID: 504e90311acb
Revises: 2042663de06d
Create Date: 2015-08-08 09:55:57.963535

"""

# revision identifiers, used by Alembic.
revision = '504e90311acb'
down_revision = '2042663de06d'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('donorinfo', 'last_donated')
    op.drop_column('donorinfo', 'birthdate')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('donorinfo', sa.Column('birthdate', postgresql.BYTEA(), autoincrement=False, nullable=False))
    op.add_column('donorinfo', sa.Column('last_donated', postgresql.BYTEA(), autoincrement=False, nullable=True))
    ### end Alembic commands ###
