"""empty message

Revision ID: 50e07b758eeb
Revises: 51122e50a689
Create Date: 2015-08-02 22:07:49.420764

"""

# revision identifiers, used by Alembic.
revision = '50e07b758eeb'
down_revision = '51122e50a689'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('donors', sa.Column('created', sa.DateTime(), nullable=False))
    op.add_column('donors', sa.Column('updated', sa.DateTime(), nullable=False))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('donors', 'updated')
    op.drop_column('donors', 'created')
    ### end Alembic commands ###
