"""empty message

Revision ID: 51122e50a689
Revises: 14a519ffc608
Create Date: 2015-08-02 22:06:16.521545

"""

# revision identifiers, used by Alembic.
revision = '51122e50a689'
down_revision = '14a519ffc608'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('donors', sa.Column('access_token', sa.String(), nullable=True))
    op.add_column('donors', sa.Column('name', sa.String(), nullable=False))
    op.add_column('donors', sa.Column('profile_url', sa.String(), nullable=False))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('donors', 'profile_url')
    op.drop_column('donors', 'name')
    op.drop_column('donors', 'access_token')
    ### end Alembic commands ###
