"""empty message

Revision ID: 5299eb02912d
Revises: 504e90311acb
Create Date: 2015-08-08 09:56:32.661378

"""

# revision identifiers, used by Alembic.
revision = '5299eb02912d'
down_revision = '504e90311acb'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('donorinfo', sa.Column('birthdate', sa.Date(), nullable=False))
    op.add_column('donorinfo', sa.Column('last_donated', sa.Date(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('donorinfo', 'last_donated')
    op.drop_column('donorinfo', 'birthdate')
    ### end Alembic commands ###
