"""empty message

Revision ID: 9263a4bff4e
Revises: 2bc9c11e348
Create Date: 2015-08-08 07:24:51.392697

"""

# revision identifiers, used by Alembic.
revision = '9263a4bff4e'
down_revision = '2bc9c11e348'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('donorinfo', sa.Column('name', sa.String(), nullable=False))
    op.alter_column('donorinfo', 'last_donated',
               existing_type=postgresql.BYTEA(),
               nullable=True)
    op.drop_constraint(u'donorinfo_donor_id_fkey', 'donorinfo', type_='foreignkey')
    op.drop_column('donorinfo', 'first_name')
    op.drop_column('donorinfo', 'last_name')
    op.drop_column('donorinfo', 'donor_id')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('donorinfo', sa.Column('donor_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('donorinfo', sa.Column('last_name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('donorinfo', sa.Column('first_name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.create_foreign_key(u'donorinfo_donor_id_fkey', 'donorinfo', 'donors', ['donor_id'], ['id'])
    op.alter_column('donorinfo', 'last_donated',
               existing_type=postgresql.BYTEA(),
               nullable=False)
    op.drop_column('donorinfo', 'name')
    ### end Alembic commands ###
